Try to fix issue #18
Couldn't reproduce it, but probably this is due to bpo-29623, which was
fixed on Mar 3, 2017.

Traceback (most recent call last):
  File "/home/.../.virtualenvs/kytos/bin/yala", line 7, in <module>
    from yala.main import main
  File "/home/.../.virtualenvs/kytos/lib/python3.6/site-packages/yala/__init__.py", line 6, in <module>
    disable_existing_loggers=False)
  File "/usr/local/lib/python3.6/logging/config.py", line 74, in fileConfig
    cp.read(fname)
  File "/usr/local/lib/python3.6/configparser.py", line 693, in read
    for filename in filenames:
TypeError: 'PosixPath' object is not iterable

Close #18